### ISSUE TITLE
Questions related with the development 

### ISSUE THREAD

**Issue by LeonJung** [ROBOTIS-GIT/open_manipulator_p#10]
1. I found that the update that happened 3 days ago suddenly starts using moveit stack. Previous release doesn't use the moveit, so I once have thought you guys are going to be independent with moveit on. So, what's the reason?

2. Does this use moveit 2.0?

3. Is there any ros2 works on schedule? or any melodic works due?

**Comment by JaehyunShim** [comment]
Hi @LeonJung 

Answers as follows, 
1. The recent update supports MoveIt! as well as our own path planning method that can function independently without using MoveIt!. We have also updated our [eManual](http://emanual.robotis.com/docs/en/platform/openmanipulator_pro/overview/) together so please refer to it for more details. 
2. No, it is not MoveIt 2.0
3. Currently, we have no plan for ROS2, but we will get to work on it in the near future. Also, we only support the Kinetic version now but I will post it on the eManual when we are done working on Melodic. Please stay tuned to our eManual. 

Have a good day and let me know if you have any other questions, 
Ryan

**Comment by LeonJung** [comment]
@RyanJaehyunShim 

Is there any reason that made you use moveit again in the package? (Previous update didn't have moveit dependencies)

The latest one seems that you put an option to make user enable to select whether using moveit or not, but  
if you put a moveit dependent source in the package together, I think that solution can not be said as moveit independent package, despite of giving option on.

**Comment by JaehyunShim** [comment]
@LeonJung 

You will understand the framework more clearly if you understand the following source file.
~/catkin_ws/src/open_manipulator_pro/open_manipulator_pro_controller/src/open_manipulator_pro_controller.cpp

If you set 'use_moveit' to false, below are used for path planning, and in that case, the framework is not dependent on MoveIt!. 
~/catkin_ws/src/robotis_manipulator/src/robotis_manipulator_trajectory_generator.cpp
~/catkin_ws/src/open_manipulator_pro/open_manipulator_pro_libs/src/kinematics.cpp

OM-PRO didn't have the MoveIt! package before because it didn't support ROS officially. 

Regards,
Ryan

**Comment by LeonJung** [comment]
@RyanJaehyunShim 

Yup, perfect

What I meant was, 
some users who don't want their packages having any dependencies with moveit might be who are having trouble with compiling/building moveit on their system (especially, when moveit has unstable master source like these days). So, for them, they should remove moveit related at line by line in the source code, even though you put use_moveit switch in the [code](https://github.com/ROBOTIS-GIT/open_manipulator_pro/blob/9a9fd54e112a9f0af88cbba2673850cc60c79175/open_manipulator_pro_controller/src/open_manipulator_pro_controller.cpp#L48).
The idea is come from the source separation and making additional cmake option to let them build as they want... but never mind.

Thanks, anyway.

**Comment by JaehyunShim** [comment]
@LeonJung 

We will consider it in future development. Please use the following [commit](https://github.com/ROBOTIS-GIT/open_manipulator_pro/commit/39fc652ca4f33d34c1999e5222448e383c714cf9), or comment out all MoveIt! related parts in the controller package.

Let us know if you have any other questions, 
Ryan

**Comment by JaehyunShim** [comment]
@LeonJung 

Now, our OpenManipulator platforms ([X](http://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros2_setup/#ros-setup), [PRO](http://emanual.robotis.com/docs/en/platform/openmanipulator_pro/overview/)) support ROS2. MoveIt! related lines are removed currently (and will be added for the next version with MoveIt! packages separated from the main controller file as your advice). Give us advice if you have any while using them. 

FYI,
Ryan
