### ISSUE TITLE
How to determine inertia values for open_manipulator_p

### ISSUE THREAD

**Issue by nicolasfrick** [ROBOTIS-GIT/open_manipulator_p#57]
Hi @rjshim,
I'd like to simulate open_manipulator_p in Gazebo and creating a custom setup. Now, I wonder which inertia values I have to take for the links of open_manipulator_p. One of two inertia tensors in link 1-6 is commented out and the other seems to satisfy only symetric objects. I tried to check the commented inertia against the values in the [specs](https://emanual.robotis.com/docs/en/platform/openmanipulator_p/specification/#specification) but neither the mass, nor the origin of COG seems to match. A hint for the correct values would be great. Thank you very much!

**Comment by JaehyunShim** [comment]
Hi @nico358,

Thank you for your interest in our manipulator. May I ask you for what purpose you need that information in your program? You would not need it unless you are trying to torque-control the robot. 

Ryan

**Comment by nicolasfrick** [comment]
Hi @rjshim,
we want to train deep learning models in simulation and apply these to our real open_manipulator_p. I think imprecise inertia values make the pretraining useless because the learned information is not correct.

**Comment by JaehyunShim** [comment]
@nico358 
Unfortunately, we do not have any further development plans for this product. @ROBOTIS-Will Any advice?

**Comment by ROBOTIS-Will** [comment]
Hi @nico358 ,
The mass and inertial information in the URDF doesn't seem to be reflecting the latest frame and hardware changes.
I'll see if I can get an accurate data from the dev team and get back to you.
Thanks!

**Comment by ROBOTIS-David** [comment]
Hi @nico358 

Thank you for raising the issue ! The wrong information on e-Manual will be fixed ASAP :) 

Have a great day.

**Comment by nicolasfrick** [comment]
Hi @ROBOTIS-David, @ROBOTIS-Will, 

that's great! Will the values be updated in urdf files as well?

Thank you very much for your support! 

@towardthesea is also joining this thread.

**Comment by ROBOTIS-David** [comment]
@JaehyunShim 
Hi Shim, 
The mass properties on the e-Manual has been updated. 
- [Check here !](https://emanual.robotis.com/docs/en/platform/openmanipulator_p/specification/#mass-property)

**Comment by JaehyunShim** [comment]
@ROBOTIS-David  Thanks :0

@nico358 

As mentioned in the last comment, the inertia data is updated on our manual. Please test with it and let us know if you have more questions. However, since Dynamixels are not torque controllable actuators I do not suggest you try any sort of torque control with the inertia data. I will close this issue.

**Comment by nicolasfrick** [comment]
Hi @ROBOTIS-David, @rjshim, @towardthesea,

thank you very much for considering my issue! I've tried the patch (https://github.com/ROBOTIS-GIT/open_manipulator_p/pull/59) with gazebo and get the following inertia visualization: 
![inertia](https://user-images.githubusercontent.com/16782483/96562414-082bac00-12c1-11eb-8871-26c672028608.png)

I think there are still problems with the inertia values. I've also noticed a discrepancy in the robot description of the urdf and the [specification] (https://emanual.robotis.com/docs/en/platform/openmanipulator_p/specification/#specification): Link1 in the spec refers to link2 in the urdf (all links are transposed by 1) and link6 inertia values was not updated. 

Link1 (mesh):
![link1](https://user-images.githubusercontent.com/16782483/96563310-175f2980-12c2-11eb-9770-a43e5484f81a.png)
Link2 (mesh):
![link2](https://user-images.githubusercontent.com/16782483/96563356-23e38200-12c2-11eb-8eb9-6a2f8eae079a.png)

**Comment by JaehyunShim** [comment]
@nico358 

Test with this [commit](https://github.com/ROBOTIS-GIT/open_manipulator_p/pull/59) and let us know if it works. We haven't tested all the features of the robot with it yet so we haven't merged it. 

Or, as @ROBOTIS-David said above, we uploaded the inertia data of each link on our [manual](https://emanual.robotis.com/docs/en/platform/openmanipulator_p/specification/#specification). Please check on it and modify the URDF file in the description folder accordingly. 

Jaehyun

**Comment by nicolasfrick** [comment]
@JaehyunShim 

I've tested the [commit ](https://github.com/ROBOTIS-GIT/open_manipulator_p/pull/59) and get the results seen in my comment (https://github.com/ROBOTIS-GIT/open_manipulator_p/issues/57#issuecomment-712705234). It looks like the COM origins are not derived with every link centered in a new reference frame. The COM origins therefore shift while adding up the failure in XYZ coordinates.  The inertia should look something like that in Gazebo: 
![Screenshot from 2020-10-25 15-38-45](https://user-images.githubusercontent.com/16782483/97111332-88497b80-16de-11eb-8774-1f65f5b9a0b4.png)

Edit: The values in the manual correspond to them in the urdf.

Nicolas
